# Generated by Django 5.0.6 on 2024-07-15 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeriaGZ', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendido',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
