# Generated by Django 5.0.6 on 2024-07-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeriaGZ', '0003_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
