# Generated by Django 5.0.6 on 2024-07-16 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeriaGZ', '0004_alter_obra_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='obra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='galeriaGZ.obra'),
        ),
    ]
