# Generated by Django 5.0.6 on 2024-07-16 20:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeriaGZ', '0006_alter_carrito_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='fecha_agregado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='obra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='galeriaGZ.obra'),
        ),
    ]
