# Generated by Django 5.0.6 on 2024-07-16 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeriaGZ', '0007_alter_carrito_fecha_agregado_alter_carrito_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galeriaGZ.obra'),
        ),
    ]
