# Generated by Django 5.0.6 on 2024-07-16 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeriaGZ', '0008_alter_carrito_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='cantidad_disponible',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
